title: brain dump
email: blog.christoph@holas.name
description: Far away from /dev/null. This is my space for jotting down notes that I'll surely forget.
twitter_username: kracherlsepp
github_username:  uniquepurpose

theme: jekyll-theme-architect
